name: advent_of_code
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0-187.0.dev
  flutter: ^3.39.0-1.0.pre-334

dependencies:
  characters: ^1.4.0
  collection: ^1.19.1
  dio: ^5.9.0
  dropdown_button2: ^3.0.0-beta.23
  dynamic_color: ^1.8.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  go_router: ^17.0.0
  intl: ^0.20.2
  leancode_hooks: ^0.1.2
  meta: ^1.17.0
  mobx: ^2.5.0
  more: ^4.6.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  vector_math: ^2.2.0

dev_dependencies:
  arb_utils:
    git: https://github.com/sbrsubuvga/arb_utils
  build_runner: ^2.10.4
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.1
  leancode_lint: ^20.0.0-dev.5
  mobx_codegen: ^2.7.4


flutter:
  uses-material-design: true
  generate: true
  config:
    enable-swift-package-manager: true

  assets:
    - assets/inputs/y2022/
    - assets/inputs/y2023/
    - assets/inputs/y2024/

  fonts:
    - family: MaterialSymbolsRounded
      fonts:
        - asset: assets/fonts/MaterialSymbolsRounded.ttf
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf
