name: advent_of_code
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0-274.0.dev
  flutter: ^3.40.0-1.0.pre-341

dependencies:
  characters: ^1.4.1
  collection: ^1.19.1
  dispose_scope: ^2.1.0
  dynamic_color: ^1.8.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^17.0.1
  intl: ^0.20.2
  leancode_hooks: ^0.1.2
  meta: ^1.17.0
  more: ^4.7.0
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4
  vector_math: ^2.2.0
  z3: ^0.1.0

dev_dependencies:
  arb_utils:
    git: https://github.com/sbrsubuvga/arb_utils
  build_runner: ^2.10.4
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.3
  leancode_lint: ^20.0.0-dev.5

flutter:
  uses-material-design: true
  generate: true
  config:
    enable-swift-package-manager: true

  assets:
    - assets/inputs/y2022/
    - assets/inputs/y2023/
    - assets/inputs/y2024/
    - assets/inputs/y2025/

  fonts:
    - family: Material Symbols Rounded
      fonts:
        - asset: assets/fonts/MaterialSymbolsRounded.ttf
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/RobotoFlex.ttf
    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/GoogleSansFlex.ttf
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP.ttf
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf
